platform :ios, '16.0'
use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

load File.expand_path('../../cocoapods/install.rb', __dir__)

target 'LookinCollectionLayoutDemo' do
  install_lookin_server_pods!(path: '../../', subspecs: ['Swift', 'MCP'])
end
